#!/usr/bin/env ruby

require 'trollop'
require 'active_support/all'

opts = Trollop::options do
  opt :distance, "In metres", type: :int
  opt :time, "In minutes.seconds format", type: :string
  opt :date, "Date of swim yyyy-mm-dd", type: :string, default: Date.today.strftime("%Y-%m-%d")
  opt :notes, "Any notes", type: :string
  opt :race, "Was this swim a race?"
end

Trollop::die :distance, "must exists" if opts[:distance].blank?

notes = opts[:notes].gsub("(", "[").gsub(")", "]") if opts[:notes]

params = {
  distance: opts[:distance],
  notes: %Q{"'#{notes}'"},
  date: opts[:date],
  race: opts[:race],
}
if opts[:time]
  minutes, seconds = opts[:time].split(".")
  params[:seconds] = (minutes.to_i * 60) + seconds.to_i
end

params = params.map { |k, v| "#{k}=#{v}" }
cmd = "heroku run rake add_swim #{params.join(" ")}"
puts cmd
system(cmd)
system("open http://swims-lucky-dip-net.herokuapp.com/")
